apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-depl
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: forms
  template:
    metadata:
      labels:
        app: forms
    spec: 
      containers:
        - name: forms
          image: dizit/forms
          env:
            - name: MONGO_URI
              value: 'mongodb://forms-mongo-srv:27017/forms'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: forms-srv
spec:
  selector:
    app: forms
  ports:
    - name: forms
      protocol: TCP
      port: 8001
      targetPort: 8001